
# ---------------------------
DEBUG = True
RELOAD = True  # 或 False，根据测试需要
GLOBAL_SCALE = 1  # 你可以根据需要修改这个值，1.0 表示不进行缩放

TEXTURE_FONT_COLOR = "#878787"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 940

ROUTINE_DIALOG_SIZE = (400, 500)
EVENT_CONTENT_MENU_SIZE = (300, 270)
COLOR_PICKER_SIZE = (400, 650)
EVENT_DIALOG_SIZE = (400, 650)

CHECKBOX_SIZE=(20, 30)
CHECKBOX_SPACING = -20
CHECKBOX_LABEL_HEIGHT = 30
CHECKBOX_LABEL_WIDTH = 150
CHECKBOX_OUTER_HEIGHT = 40

# ---------------------------
# 尺寸设置
TOP_SCALE_AREA_HEIGHT = 300
DRAWING_AREA_HEIGHT = 300
BOTTOM_SCALE_AREA_HEIGHT = 500
FUNCTION_AREA_HEIGHT = 400
HALF_HOUR_WIDTH = 40

HOUR_WIDTH = 2 * HALF_HOUR_WIDTH
TIMELINE_WIDTH = 168 * HOUR_WIDTH
TIMELINE_HEIGHT = BOTTOM_SCALE_AREA_HEIGHT + DRAWING_AREA_HEIGHT + TOP_SCALE_AREA_HEIGHT

STAMP_BUTTON_SPACING = 0
STAMP_BUTTON_WIDTH = 2 * HOUR_WIDTH
STAMP_BUTTON_HEIGHT = FUNCTION_AREA_HEIGHT // 2
STAMP_IMAGE_HEIGHT = HOUR_WIDTH
STAMP_BUTTON_SIZE = 2 * HOUR_WIDTH

STAMP_SCALE = 0.9
STAMP_WIDTH = HOUR_WIDTH
STAMP_HEIGHT = HOUR_WIDTH
HALF_STAMP_WIDTH = HALF_HOUR_WIDTH
HALF_STAMP_HEIGHT = HOUR_WIDTH
STAMP_SIZE = (STAMP_WIDTH, STAMP_HEIGHT)
HALF_STAMP_SIZE = (HALF_STAMP_WIDTH, HALF_STAMP_HEIGHT)
SCALED_STAMP_SIZE = (int(HOUR_WIDTH * STAMP_SCALE), int(HOUR_WIDTH * STAMP_SCALE))
SCALED_HALF_STAMP_SIZE = (int(HALF_HOUR_WIDTH * STAMP_SCALE), int(HOUR_WIDTH * STAMP_SCALE))
STAMP_SIZE_HINT = (1, 1)

LOWER_SCALE_HEIGHT = HOUR_WIDTH
UPPER_SCALE_HEIGHT = HOUR_WIDTH
LOWER_SCALE_Y = BOTTOM_SCALE_AREA_HEIGHT // 2 - LOWER_SCALE_HEIGHT
UPPER_SCALE_Y_VERSUS_TOP_SCALE_Y = HALF_HOUR_WIDTH * 1.25
UPPER_SCALE_Y = BOTTOM_SCALE_AREA_HEIGHT + DRAWING_AREA_HEIGHT + UPPER_SCALE_Y_VERSUS_TOP_SCALE_Y

SCALE_HEIGHT = HOUR_WIDTH

ROUTINE_Y = HALF_HOUR_WIDTH
ROUTINE_HEIGHT = TIMELINE_HEIGHT - 2 * ROUTINE_Y
ROUTINE_TEXT_Y = LOWER_SCALE_Y + LOWER_SCALE_HEIGHT
ROUTINE_TEXT_Y_MAX = BOTTOM_SCALE_AREA_HEIGHT
ROUTINE_WIDTH = HALF_HOUR_WIDTH

EVENT_Y = BOTTOM_SCALE_AREA_HEIGHT
EVENT_HEIGHT = DRAWING_AREA_HEIGHT
EVENT_TEXT_UPPER_PADDING = HALF_HOUR_WIDTH//2

EVENT_BORDER_THICKNESS = 4
ROUTINE_BORDER_THICKNESS = 3
SCALE_BORDER_THICKNESS = 4

# ---------------------------
# 字体设置
UI_FONT = "wqy_zenhei"
STYLE_FONT = "KingHwa_OldSong"

TEXTURE_FONT = STYLE_FONT
SCALE_FONT = STYLE_FONT
EVENT_FONT = STYLE_FONT
TEXT_INPUT_FONT = STYLE_FONT

COLOR_INPUT_FONT = UI_FONT

TITLE_FONT = UI_FONT
BUTTON_FONT = UI_FONT
CHECKBOX_LABEL_FONT = UI_FONT
LABEL_FONT = UI_FONT

SCALE_FONT_SIZE = 50
EVENT_FONT_SIZE = 45
ROUTINE_FONT_SIZE = 30

ROUTINE_LINE_HEIGHT = 1.5

# ---------------------------

DIALOG_NEW_BG_RGB = (235,159,154, 0.9)
DIALOG_NEW_BG_RGB = (DIALOG_NEW_BG_RGB[0] / 255, DIALOG_NEW_BG_RGB[1] / 255,
                     DIALOG_NEW_BG_RGB[2] / 255, DIALOG_NEW_BG_RGB[3])
DIALOG_LABEL_RGB = (1, 1, 1, 1)
DIALOG_BG_RGB = (0.157, 0.157, 0.157, 0.7)
# 每小时宽度（横向单位）
BACKGROUND_TRANSPARENCY = 1

FULL_STAMP_ACTIVE_COLOR = "#FF8A85"        # 黄色
HALF_STAMP_ACTIVE_COLOR = "#FF8000"        # 黄色
STAMP_INACTIVE_COLOR = "#111111"  # 灰色

STAMP_BUTTON_TEXT_FONT = "KingHwa_OldSong"
STAMP_BUTTON_TEXT_SIZE = 30
STAMP_BUTTON_TEXT_COLOR = "#FFFFFF"


# 印章



# 最底层颜色参数
REGION_SCALE_BG_COLOR = "#141717"  # 刻度区背景色（上部和下部）
REGION_DRAWING_BG_COLOR = "#141717"  # 绘图区背景色
REGION_LINE_COLOR = "#4D4D4D"  # 虚线/网格线颜色

# 刻度区
# 刻度区间数组（按一天 24 小时划分）
TOPIC_SCALE_INTERVALS = [[0, 6], [6, 9], [9, 12], [12, 15], [15, 18], [18, 24]]
# 刻度区间文字数组，左对齐以指示该区间的开始时间
TOP_SCALE_TEXTS = ["零點", "六點", "九點", "十二點", "十五點", "十八點"]
# 刻度区间填充色（按一天 24 小时分为 4 个区间）
TOP_SCALE_COLOR_INTERVAL_FILL = ["#4B4B4B", "#FFD966", "#FFD966", "#FF9999", "#FF9999", "#FFB366"]
# 刻度区间边框色（均为白色）
TOP_SCALE_INTERVAL_BORDER_COLOR = ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"]
# 刻度区间文字颜色
TOP_COLOR_INTERVAL_TEXT_COLOR = ["#FFFFFF", "#000000", "#000000", "#000000", "#000000", "#000000"]



# 刻度文字字体（中文字体，可根据实际情况修改）

# 刻度对齐方式：左对齐（本例中仅实现左对齐）
SCALE_TEXT_ALIGN = "left"

# ---------------------------
# 刻度区参数

DASH_LENGTH = 5

EVENT_BORDER_COLOR = "#000000"  # 事件方块边框颜色（白色）
  # 事件方块边框线宽

ROUTINE_BOTTOM = 50

ROUTINE_TEXT_INSERT = " "

# 事件相关参数




#
